import os
import re
from dotenv import load_dotenv

from langchain.agents import create_agent
from langchain_openai import ChatOpenAI
from langchain.tools import tool

from duckduckgo_search import DDGS
import wikipedia


load_dotenv()


# -----------------------------
# Tool 1: Web Search Tool
# -----------------------------
@tool
def web_search(query: str) -> str:
    """
    Search the web and return top results.
    """
    try:
        results = []
        with DDGS() as ddgs:
            search_results = ddgs.text(query, max_results=5)

            for r in search_results:
                title = r.get("title", "No title")
                snippet = r.get("body", "No snippet")
                url = r.get("href", "No URL")

                results.append(
                    f"Title: {title}\n"
                    f"Snippet: {snippet}\n"
                    f"URL: {url}"
                )

        if not results:
            return "No web results found."

        return "\n\n".join(results)

    except Exception as e:
        return f"Web search error: {str(e)}"


# -----------------------------
# Tool 2: Wikipedia Tool
# -----------------------------
@tool
def wikipedia_search(query: str) -> str:
    """
    Search Wikipedia and return summaries.
    """
    try:
        titles = wikipedia.search(query, results=3)

        if not titles:
            return "No Wikipedia results found."

        output = []

        for title in titles:
            try:
                summary = wikipedia.summary(title, sentences=4, auto_suggest=False)
                page = wikipedia.page(title, auto_suggest=False)

                output.append(
                    f"Title: {page.title}\n"
                    f"Summary: {summary}\n"
                    f"URL: {page.url}"
                )
            except Exception:
                continue

        if not output:
            return "Wikipedia pages found, but summaries could not be extracted."

        return "\n\n".join(output)

    except Exception as e:
        return f"Wikipedia search error: {str(e)}"


# -----------------------------
# Build LLM
# -----------------------------
def get_llm():
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY not found in .env file.")

    return ChatOpenAI(
        model="gpt-4.1-mini",
        temperature=0.2
    )


# -----------------------------
# Prompt
# -----------------------------
SYSTEM_PROMPT = """
You are an Autonomous Research Agent for a university assignment.

Your tasks:
1. Take a topic as input.
2. Research the topic using available tools.
3. Use BOTH tools at least once:
   - web_search
   - wikipedia_search
4. Analyze the information.
5. Generate a detailed report in markdown format.

Rules:
- Keep the writing simple, clear, and academic.
- Do not invent facts.
- If something is uncertain, mention it clearly.
- Avoid unnecessary repetition.

The final report MUST include these sections exactly:

# Cover Page
- Assignment: Autonomous Research Agent (LangChain)
- Topic: <topic>
- Generated by: LangChain Research Agent

# Title

# Introduction

# Key Findings

# Challenges

# Future Scope

# Conclusion

# Sources Used

Formatting rules:
- Under Key Findings, use numbered points.
- Under Sources Used, include source names and URLs when possible.
"""


# -----------------------------
# Create Agent
# -----------------------------
def build_agent():
    llm = get_llm()

    agent = create_agent(
        model=llm,
        tools=[web_search, wikipedia_search],
        system_prompt=SYSTEM_PROMPT
    )

    return agent


# -----------------------------
# Extract final output text
# -----------------------------
def extract_final_text(result) -> str:
    if isinstance(result, str):
        return result

    if isinstance(result, dict):
        if "output" in result and isinstance(result["output"], str):
            return result["output"]

        if "messages" in result and result["messages"]:
            last_msg = result["messages"][-1]
            content = getattr(last_msg, "content", "")

            if isinstance(content, str):
                return content

            if isinstance(content, list):
                parts = []
                for item in content:
                    if isinstance(item, str):
                        parts.append(item)
                    elif isinstance(item, dict) and "text" in item:
                        parts.append(item["text"])
                return "\n".join(parts)

    return str(result)


# -----------------------------
# Generate report
# -----------------------------
def generate_report(topic: str, save_file: bool = True) -> str:
    agent = build_agent()

    user_prompt = f"""
Research the following topic and generate a structured report:

Topic: {topic}

Requirements:
- Search relevant information
- Extract key insights
- Organize the content
- Generate a detailed report

Mandatory sections:
- Cover Page
- Title
- Introduction
- Key Findings
- Challenges
- Future Scope
- Conclusion
- Sources Used

Remember:
- You must use BOTH tools before giving the final answer.
"""

    result = agent.invoke(
        {
            "messages": [
                {"role": "user", "content": user_prompt}
            ]
        }
    )

    report = extract_final_text(result)

    if save_file:
        safe_name = re.sub(r"[^a-zA-Z0-9]+", "_", topic.strip().lower()).strip("_")
        filename = f"{safe_name}_report.md"

        with open(filename, "w", encoding="utf-8") as f:
            f.write(report)

        print(f"\nReport saved as: {filename}")

    return report


# -----------------------------
# Main function
# -----------------------------
def main():
    print("=== Autonomous Research Agent (LangChain) ===")
    topic = input("Enter your research topic: ").strip()

    if not topic:
        print("Please enter a valid topic.")
        return

    report = generate_report(topic)

    print("\n" + "=" * 100 + "\n")
    print(report)


if __name__ == "__main__":
    main()
